### ISSUE TITLE
DND option for Omnipod alarms (alarm override)

### ISSUE THREAD

**Issue by taylorpatterson007** [cfaagaard/LoopDashboard#12]
Can the Omnipod alarms be over ridden by Loop? 

As a Loop user, I want the option to set a Do Not Disturb period so that if my Omnipod expires in the middle of the night, the screamer alarm doesn't wake me up at 3am. Perhaps Loop/Omnipod can obey the iPhone's Sleep/Wake Up settings for DND?

**Comment by cfaagaard** [comment]
This repository is only about the loopdashboard. Your issue should be created in another loop repository. Maybe this : https://github.com/LoopKit/Loop

**Comment by taylorpatterson007** [comment]
Sorry and thank you

 

From: cfaagaard ***@***.***>
Reply-To: cfaagaard/LoopDashboard ***@***.***>
Date: Friday, May 13, 2022 at 10:59 AM
To: cfaagaard/LoopDashboard ***@***.***>
Cc: Taylor Patterson ***@***.***>, Author ***@***.***>
Subject: Re: [cfaagaard/LoopDashboard] DND option for Omnipod alarms (alarm override) (Issue #12)

 

This repository is only about the loopdashboard. Your issue should be created in another loop repository. Maybe this : https://github.com/LoopKit/Loop
